name: Publish model to edge device
run-name: ${{ github.actor }} is publishing to edge device
on:
  workflow_dispatch:
jobs:
  Publish-To-Edge:
    runs-on: ubuntu-latest
    steps:
      - run: export DOCKER_CLI_EXPERIMENTAL=enabled
        name: set docker cli experimental = true
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: pip install azure-cognitiveservices-vision-customvision
      - run: python fetch_model.py
      - run: ls
      - run: unzip exported_model.zip
      - run: ls
      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
         docker run --rm --privileged docker/binfmt:66f9012c56a8316f9244ffd7622d7c21c1f6f28d
         docker buildx create --use --name multi-arch-builder
         docker buildx build --platform linux/armhf -t familyGuy.azurecr.io/classifier:v2 .
         docker push familyGuy.azurecr.io/classifier:v2
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az account show
            az storage -h
