name: Publish model to edge device
run-name: ${{ github.actor }} is publishing to edge device
on:
  workflow_dispatch:
jobs:
  Publish-To-Edge:
    runs-on: ubuntu-latest
    steps:
      - run: export DOCKER_CLI_EXPERIMENTAL=enabled
        name: set docker cli experimental = true
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: Login to Azure using Azure/login@v1
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: pip install azure-cognitiveservices-vision-customvision
      - run: python fetch_model.py
      - run: unzip exported_model.zip
      -
        name: Set up QEMU dependency
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build image
        uses: docker/build-push-action@v4
        with:
          tags: familyGuy.azurecr.io/classifier:v2
          platforms: linux/armhf
          context: .
          push: false
          load: true
      
      - run: |
            docker image ls
            
      - name: 'Login to ACR using azure/docker-login@v1'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      - name: 'Login to ACR (docker/login-action@v2)'
        uses: docker/login-action@v2
        with:
          registry: familyGuy.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      - name: Push image to ACR
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az acr login -n familyGuy
            docker push familyGuy.azurecr.io/classifier:v2
        
